version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      # These values are taken from the .env file
      MYSQL_DATABASE: ${CB_DB_NAME}
      MYSQL_USER: ${CB_DB_USERNAME}
      MYSQL_PASSWORD: ${CB_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    volumes:
      - chartbrew-db:/var/lib/mysql

  chartbrew:
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      # Feel free to remap these ports on the left side to your desired ports
      - 4018:4018 # Frontend
      - 4019:4019 # API
    depends_on:
      - db
    links:
      - db

volumes:
  chartbrew-db: